"""Add stock_status to flowers

Revision ID: add_stock_status
Revises: edef582d8750
Create Date: 2026-01-15

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_stock_status'
down_revision = 'edef582d8750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flowers', sa.Column('stock_status', sa.String(length=20), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE flowers SET stock_status = 'in_stock' WHERE stock_status IS NULL")
    # Make it not nullable
    op.alter_column('flowers', 'stock_status', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flowers', 'stock_status')
    # ### end Alembic commands ###
